### ISSUE TITLE
Proposer une visualisation complète des différentes variables

### ISSUE THREAD

**Issue by ipante** [astonedf/D3_LoLChampStats#4]
Il est sans doute rare qu'un choix/qu'une comparaison ne s'effectue que sur une dimension (attaque, défense, armure). Veillez à proposer une vue qui affiche toutes ces dimensions en même temps, soit par simple superposition des lignes, soit (préférable) au travers d'une visualisation ad hoc (pourquoi pas un radar par exemple ?). A noter que cette vue pourrait être proposée indépendamment de toute comparaison.

**Comment by astonedf** [comment]
Non en effet, le seul souci c'est l'échelle qui change beaucoup suivant la dimension (2200 pour les points de vie et 60 pour le résistance magique par exemple), donc la visualisation ne serait pas très lisible. Cependant j'ai crée une deuxième visualisation en barplot avec des % pour rapidement comparer toutes les dimensions. (Bientôt finie, j'aimerais encore ajouter un slider pour sélectionner le niveau des champions)

**Comment by ipante** [comment]
Faites-moi signe dès que ce sera fait :)

**Comment by astonedf** [comment]
Est-ce que c'est tout bon pour le projet?
